### ISSUE TITLE
Some Exception When Installing ScintillaNET via NuGet.

### ISSUE THREAD

**Issue by JohnyMac** [jacobslusser/ScintillaNET#170]
Hello, 

When updating to latest ScintillaNET, I keep getting this exception: 
```
Attempting to gather dependencies information for package 'jacobslusser.ScintillaNET.3.5.5' with respect to project 'TestScintilla', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'jacobslusser.ScintillaNET.3.5.5' with DependencyBehavior 'Lowest'
Resolving actions to install package 'jacobslusser.ScintillaNET.3.5.5'
Resolved actions to install package 'jacobslusser.ScintillaNET.3.5.5'
Install failed. Rolling back...
Package 'jacobslusser.ScintillaNET 3.5.5' does not exist in project 'TestScintilla'
Package 'jacobslusser.ScintillaNET 3.5.5' does not exist in folder 'C:\Users\Johny\Documents\Visual Studio 2015\Projects\TestScintilla\packages'
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Protocol.Core.v3.GlobalPackagesFolderUtility.<AddPackageAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.Core.v3.DownloadResourceV3.<GetDownloadResourceResultAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()
========== Finished ==========
```

I tried it to install it in a new project and same thing happens.

**Comment by JohnyMac** [comment]
Forgot to say, This problem is in Scintilla only, Tried to install/update several other packages and all worked.

**Comment by jacobslusser** [comment]
It's possible that I borked the nuget package, but I can't reproduce this issue. I've tried creating a new empty Windows Forms project and adding the ScintillaNET package from nuget.org and don't have any issues.

**Comment by JohnyMac** [comment]
I tried to install an old version and it worked so it bugs only with the 3.5.5 version.
I tried various ways and all resulted in the same error, however, didn't test on another computer yet.

**Comment by jacobslusser** [comment]
What version of VS and nuget are you using? If you browse to your packages folder, do you see the package there? Are you sure the framework version of the project you are adding it to is the same as the one ScintillaNET is built for? Are you sure you are installing the package into the project and not the solution? Did you recently make any changes to your nuget.config?

I'm reaching here because I don't have a ready answer...

**Comment by jacobslusser** [comment]
@JohnyMac,

I updated my nuget.exe command line tool and repackaged v3.5.5 for you -- just in case the issue is that my nuget tool is too old or something. Please give these a try and see if you have any more luck. If you've never loaded a NuGet package locally before, it's really easy.

1. Drop these files in a folder on your machine
2. Remove the .zip extension I had to append to the end of the files to get them uploaded to GitHub
3. Add the folder path you placed them in to your list of NuGet package sources in Visual Studio
4. Temporarily uncheck the box next to the official nuget.org package source or place the local folder source higher in the priority than nuget.org 

Let me know if you have any more luck with these.

[jacobslusser.ScintillaNET.3.5.5.nupkg.zip](https://github.com/jacobslusser/ScintillaNET/files/83783/jacobslusser.ScintillaNET.3.5.5.nupkg.zip)
[jacobslusser.ScintillaNET.Signed.3.5.5.nupkg.zip](https://github.com/jacobslusser/ScintillaNET/files/83784/jacobslusser.ScintillaNET.Signed.3.5.5.nupkg.zip)

**Comment by JohnyMac** [comment]
This worked great, Thanks

Make sure to update the original package source too for future updates ;)

**Comment by jacobslusser** [comment]
Of course NuGet doesn't allow me to update the existing package so I had to rev the whole project to v3.5.6 and publish a [new release](https://github.com/jacobslusser/ScintillaNET/releases/tag/v3.5.6) and NuGet packages. That was a pain.

Lesson learned -- always use the most current version of NuGet when creating packages...

**Comment by JohnyMac** [comment]
Just wanted to confirm that it worked great :)

**Comment by jacobslusser** [comment]
Awesome. :)
