### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#243]
Hi,

Sometimes, my application crashes at the bellow stack trace:

`Stack:    at ScintillaNET.GapBuffer``1.get_Item(Int32 index)
   at ScintillaNET.LineCollection.CharLineLength(Int32 index)
   at ScintillaNET.LineCollection.DeletePerLine(Int32 index)
   at ScintillaNET.LineCollection.TrackDeleteText(SCNotification scn)
   at ScintillaNET.LineCollection.scintilla_SCNotification(Object sender, SCNotificationEventArgs e)
   at ScintillaNET.Scintilla.WmReflectNotify(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

What is this? Why that is happening? Any way we can handle that?

Regards,

**Comment by jacobslusser** [comment]
Is it possible you are closing/disposing of the instance and then trying to access it? Or are you forgetting to use the opt-in behavior we discussed in issue #85?
