### ISSUE TITLE
Exception System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by Aghlara** [jacobslusser/ScintillaNET#405]
Type: System.IndexOutOfRangeException
Message: Index was outside the bounds of the array.
Source: ScintillaNET
Stack:    at ScintillaNET.GapBuffer`1.get_Item(Int32 index)
  at ScintillaNET.LineCollection.CharLineLength(Int32 index)
  at ScintillaNET.LineCollection.DeletePerLine(Int32 index)
  at ScintillaNET.LineCollection.TrackDeleteText(SCNotification scn)
  at ScintillaNET.LineCollection.scintilla_SCNotification(Object sender, SCNotificationEventArgs e)
  at ScintillaNET.Scintilla.WmReflectNotify(Message& m)
  at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Is there anyway we can handle this exception?

**Comment by jacobslusser** [comment]
You shouldn't be receiving this exception. It is likely you are doing something with Scintilla outside the standard API. Maybe you can explain more what is causing it.
